services:
  mongodb:
    image: mongo:latest
    container_name: "mongo_db"
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: CompanyDB # Optional: specify a default database
    volumes:
      - mongodb_data:/data/db
      - ./scripts:/docker-entrypoint-initdb.d # Mount a local 'scripts' directory
  nodejs:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: "assign3_server"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app
    depends_on:
      - mongodb
volumes:
  mongodb_data:
